function RadarInfo=read_xsl_info_f(File_Name)
% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: D:\Spectrum-Share\NASCTN 3.5 GHz San Diego Release\File_Parameters.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2016/11/07 17:09:25

%% Import the data

[~, ~, raw] = xlsread(File_Name,'Sheet1','','basic');
raw = raw(2:end,:);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,[1,2,3,6]);
raw = raw(:,[4,5]);

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
RadarInfo.Filename = cellVectors(:,1);
RadarInfo.Antenna = cellVectors(:,2);
RadarInfo.Comments = cellVectors(:,3);
RadarInfo.RFcenterfrequencyHz = data(:,1);
RadarInfo.ADCscalefactorFADC = data(:,2);
%RadarInfo.SHA1Hash = cellVectors(:,4);

%% Clear temporary variables
clearvars data raw cellVectors R;
end